local L0_1, L1_1
L0_1 = {}
L0_1.Reliquary_Main_Affix_NONE = 0
L0_1.Reliquary_Main_Affix_TOUGH = 1
L0_1.Reliquary_Main_Affix_STRONG = 2
L0_1.Reliquary_Main_Affix_RUTHLESS = 3
L0_1.Reliquary_Main_Affix_FATAL = 4
L0_1.Reliquary_Main_Affix_GLORY = 5
L0_1.Reliquary_Main_Affix_EMINENCE = 6
L0_1.Reliquary_Main_Affix_EXULTATION = 7
L0_1.Reliquary_Main_Affix_CRUEL = 8
L0_1.Reliquary_Main_Affix_HOLINESS = 9
L0_1.Reliquary_Main_Affix_FIERCE = 10
L0_1.Reliquary_Main_Affix_WISDOM = 11
L0_1.Reliquary_Main_Affix_CONCENTRATION = 12
ReliquaryMainAffixName = L0_1
